version: '3.8'

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306" 
    environment:
      MYSQL_DATABASE: projectdb
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/var/lib/mysql

