version: '3.8'
services:
  db:
    image: mongo:7.0.0
    container_name: api-db
    profiles:
      - dev
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./docker/database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: projectdb
  db_test:
    image: mongo:7.0.0
    container_name: db-test
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    tmpfs: 
      - /data/db
  mongo-express:
    image: mongo-express
    restart: always
    profiles:
      - dev
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=root
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root